### ISSUE TITLE
Question about report settings

### ISSUE THREAD

**Issue by HandiYin** [gereon-t/trajectopy#1]
Hi! I have tried this toolbox to compare trajectoies and it's really easy to use and elegant! 
While I was viewing the report, I have a question about direction decomposition: 'along', 'cross-h' and 'cross-v'. When I check the report settings I found the description are :Pos Dir Dev x/y/z. I'm still confused, can u add some instructions on this?
Thanks!

**Comment by gereon-t** [comment]
Hello! Thank you very much for your feedback! I added a figure to the readme (report settings section) that explains the directed ATE deviations in more detail. In short, these are the vehicle-fixed deviations along the direction of travel, across the direction of travel (cross-h(orizontal)) and vertical to the direction of travel (cross-v). If you prefer different names, you can change these in the report settings. Alternatively you can turn directed position deviations off entirely by unchecking the "Directed ATE" checkbox.

**Comment by gereon-t** [comment]
Solved in commit 8e0d6629fed0cd9a556c013d759158db38e80732

**Comment by HandiYin** [comment]
Thanks! This solves my problem. Really impressive toolbox~
